### ISSUE TITLE
Titles submitted with Markdown header # symbol.

### ISSUE THREAD

**Issue by EdOverflow** [fransr/bountyplz#1]
Hey Frans,

When submitting a report, I noticed that the title contains the Markdown header symbol `#` as seen below. For some reason, the title in your screenshot is different to mine.

![image](https://user-images.githubusercontent.com/18099289/38944756-f2f303c8-4334-11e8-8c03-035f10afe362.png)

```
--- attributes:
title: # Unauthenticated reflected XSS in example.com via the p parameter.
program: utopia-test
weakness: xss reflected
inline-attachments: img1.png,file2.png,file3.png,file4.png,ok.mp4
---
```

## Steps to reproduce

1. Create a Markdown report with the following contents:

~~~
---
weakness: "xss reflected"
---

# Unauthenticated reflected XSS in example.com via the p parameter.

This is cool!

# Another title

```
Testing 1234
```

## Impact

This is the impact, go for it!
~~~

2. Submit the report;

```
$ bountyplz h1 program report.md
```

3. Navigate to the submitted report.

## Setup

I am running this tool on Ubuntu 17.10.

**Comment by fransr** [comment]
Fix should be in: https://github.com/fransr/bountyplz/commit/c5304a3c999f80eda61784545e27c472d95e7ff7

The issue was some reports failing depending on `ggrep` and `grep`, so I made sure the grep always ended up in exit code 0, but I made an error in the `||` after the grep. Should work now!
